### ISSUE TITLE
Cannot login to server

### ISSUE THREAD

**Issue by capsulecorplab** [lmco/mbee#2]
Following the [Tutorial: API Authentication and Pulling Data](https://github.com/lmco/mbee/blob/master/doc/tutorial-001:-API-authentication.md), I get a `KeyError` when attempting to store token at `token = res['token']                      # store the auth token for later`.

**Comment by josh-kaplan** [comment]
On the client side:
What is the the server response status code being printed?
If you print the response JSON what do you get?
On the server side:
What authentication strategy are you using? Or is it the default (local) strategy provides in the default config?
Have you made any configuration changes from the default?
Can you provide any output from the server logs?

**Comment by capsulecorplab** [comment]
I was getting a 401 server response status with the response:
`{'status': 401, 'message': 'Unauthorized', 'description': 'Invalid password.'}`
on the client side, using (what I thought was) the default authentication scheme on the server side. But, looking at https://github.com/lmco/mbee/blob/13f679f3c923c2bc39467e2359df0e7aeba3b1e0/config/default.cfg#L52, I realized the default admin password wasn't `CHANGE_ME`.

Should this be reflected in the documentation? It might not be entirely clear to readers where to lookup the default authentication username/password, let alone, how to change it.

I get a 200 server response status after changing the password, but now I'm getting a 401 response status for the "# Check version" request:
```
# Check version
url = '{}/api/version'.format(server)
auth_header = {'Authorization': 'Bearer {}'.format(token)}
r = requests.get(url, headers=auth_header)
res = r.json()
print r.status_code
print res
```
yields
```
Traceback (most recent call last)
<ipython-input-14-808aee4582a3> in <module>
      3 auth_header = {'Authorization': 'Bearer {}'.format(token)}
      4 r = requests.get(url, headers=auth_header)
----> 5 res = r.json()
      6 print(r.status_code)
      7 print(res)

~/.pyenv/versions/3.6.8/lib/python3.6/site-packages/requests/models.py in json(self, **kwargs)
    895                     # used.
    896                     pass
--> 897         return complexjson.loads(self.text, **kwargs)
    898 
    899     @property

~/.pyenv/versions/3.6.8/lib/python3.6/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:
    356         cls = JSONDecoder

~/.pyenv/versions/3.6.8/lib/python3.6/json/decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

~/.pyenv/versions/3.6.8/lib/python3.6/json/decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ajbieber** [comment]
It appears that there are two minor fixes that need to be made here...

The first (which you stated above) is that the admin password in the first tutorial is not the same password that is set by default in the `default.cfg`. That being said, there is a section in the documentation which details the default admin and where to change the username/password:

https://github.com/lmco/mbee/blob/13f679f3c923c2bc39467e2359df0e7aeba3b1e0/doc/1.0-getting-started.md#L76-L83

The second is that a failed login while using an invalid/incorrect token does not return proper JSON. This is why you are experiencing the JSONDecodeError. I personally have not been able to replicate your second 401 error. I believe that your token may have not been properly set when running the "Login to the server" section. The token we get from that request is the token that gets used in the following section. Try making the login request one more time with the correct password: `auth_header = ('admin', 'Admin12345!')`, and then using that token value to make the GET version request again.

If it is still failing after that, please provide the token value that you sent in the GET version request for better debugging.

**Comment by capsulecorplab** [comment]
Not sure what happened, but ended up restarting my Python REPL and rerunning everything with the correct password. The GET version request works now, thanks!
