### ISSUE TITLE
Remove colons from filenames

### ISSUE THREAD

**Issue by sanbales** [lmco/mbee#3]
Having filenames with `:` breaks NTFS.

The easiest solution I can think of is to rename the files in `doc/` to not have a colon in them.

I'd offer a PR, but I can't even checkout the files to make the fix unless I do it by manually copying the raw from github, but that would mean that we would lose the history on those files.

This is what I get when I do a status and an `ls` in my filesystem:

![image](https://user-images.githubusercontent.com/1438114/58138779-cc8d3e00-7c05-11e9-9216-ddb7bfb5af0c.png)

**Comment by josh-kaplan-lm** [comment]
We have a patch prepared. We should be able to release a patch update today.

**Comment by sanbales** [comment]
Thank you @josh-kaplan-lm !

**Comment by josh-kaplan-lm** [comment]
0.8.1 was released which addresses this issue per the recommended fix above.
